# Generated by Django 3.0.2 on 2020-01-26 14:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(default=True)),
                ('expected_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField()),
                ('sub_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Task.TaskList')),
            ],
        ),
    ]
