# Generated by Django 3.0.2 on 2020-01-26 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='status',
        ),
        migrations.RemoveField(
            model_name='tasklist',
            name='sub_task',
        ),
    ]
