# Generated by Django 3.0.2 on 2020-01-27 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0006_auto_20200127_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='expected_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='sub_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Task.TaskList'),
        ),
    ]
