# Generated by Django 3.0.2 on 2020-01-27 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0007_auto_20200128_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='expected_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='status',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='sub_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Task.TaskList'),
        ),
    ]
