# Generated by Django 3.0.2 on 2020-01-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0008_auto_20200128_0345'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listName', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=300)),
                ('expected_time', models.TimeField(null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TaskList',
        ),
    ]
