# Generated by Django 3.0.2 on 2020-01-30 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0009_auto_20200128_2024'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='List',
            new_name='AddList',
        ),
        migrations.RenameModel(
            old_name='Task',
            new_name='AddTask',
        ),
    ]
