# Generated by Django 3.0.2 on 2020-01-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0011_auto_20200130_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtask',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
